import type { Quality, Watchlist } from '@crypto-screener/contracts';
import { InfoTip } from '@/components/ui/Tooltip';
import {
  type BriefingCandidate,
  briefingBlocks,
  briefingWrittenWithoutTools,
  parseBriefing,
} from '@/lib/briefing';
import { lookupBias, lookupMetric, lookupRegimeState } from '@/lib/copy';
import { fmtNum } from '@/lib/format';
import { parseMacroEvents, selectMacroBanner } from '@/lib/macro-events';
import { num, pct, signedPct, str } from '@/lib/payload';
import { coingeckoGlobalUnavailable } from '@/lib/provider-status';
import { marketVerdict, regimeState, sieveStages } from '@/lib/verdict';
import { sideMeta } from '../watchlist/WatchlistTable';
import { Sieve } from './Sieve';

export interface MarketStageProps {
  regime: unknown;
  marketContext: unknown;
  validation: unknown;
  quality: Quality;
  providerStatus: unknown;
  run: { row_count: number };
  watchlists: Watchlist[];
}

/**
 * The hero: a plain-English market verdict, the sieve funnel (real pipeline counts), and the
 * stat tiles. Server Component -- only the sieve's final segment needs a client boundary, and
 * that's isolated inside <Sieve>.
 */
export function MarketStage({
  regime,
  marketContext,
  validation,
  quality,
  providerStatus,
  run,
  watchlists,
}: MarketStageProps) {
  const verdict = marketVerdict({ regime, market_context: marketContext, validation });
  const stages = sieveStages({ provider_status: providerStatus, run, quality, watchlists });
  const coingeckoUnavailable = coingeckoGlobalUnavailable(providerStatus);
  const macroBanner = selectMacroBanner(parseMacroEvents(marketContext), new Date());
  const briefing = parseBriefing(marketContext);

  const state = regimeState(regime);
  const marketCapChange = num(marketContext, 'market_cap_change_24h_pct');
  const fearGreedValue = num(marketContext, 'fear_greed_value');
  const fearGreedClassification = str(marketContext, 'fear_greed_classification');
  const meanBtcCorrelation = num(marketContext, 'mean_btc_correlation');
  const altAltMeanCorrelation = num(marketContext, 'alt_alt_mean_correlation');
  const altAltCorrelationPairs = num(marketContext, 'alt_alt_correlation_pairs');
  const correlationSpread = num(marketContext, 'correlation_spread');

  return (
    <section className="stage" aria-label="The market">
      <h2 className="stage-eyebrow m-0">The market</h2>
      <h3 className="verdict m-0 mt-2">
        {verdict.headline}
        <span
          aria-hidden="true"
          className="ml-2 inline-block h-[1em] w-[0.55em] translate-y-[0.12em] animate-blink bg-ink motion-reduce:animate-none"
        />
      </h3>
      <p className="verdict-sub">{verdict.summary}</p>
      {macroBanner.upcoming ? (
        <div role="status" className="staleness-banner mt-4">
          {macroBanner.upcoming}
        </div>
      ) : null}
      {macroBanner.recent ? (
        <div role="status" className="staleness-banner mt-4">
          {macroBanner.recent}
        </div>
      ) : null}
      {briefing ? (
        <div className="mt-4">
          <div className="label">Tonight's read</div>
          {briefingBlocks(briefing.text).map((block) =>
            block.kind === 'prose' ? (
              <p key={block.text} className="verdict-sub">
                {block.text}
              </p>
            ) : (
              <div
                key={block.items.map((item) => `${item.symbol}:${item.side}`).join(',')}
                className="mt-1"
              >
                {block.items.map((item) => (
                  <BriefingCandidateRow key={`${item.symbol}:${item.side}`} item={item} />
                ))}
              </div>
            ),
          )}
          <p className="text-ash text-xs font-mono">generated by {briefing.model}</p>
          {briefingWrittenWithoutTools(briefing) ? (
            <p className="text-ash text-xs font-mono">written without data lookups</p>
          ) : null}
        </div>
      ) : null}
      {verdict.facts.length > 0 ? (
        <ul className="mt-4 grid max-w-[62ch] list-none gap-1.5 p-0 text-[13px] text-muted">
          {verdict.facts.map((fact) => (
            <li key={fact}>{fact}</li>
          ))}
        </ul>
      ) : null}

      <div className="mt-10">
        <Sieve stages={stages} />
      </div>

      <div className="mt-8 flex flex-wrap gap-x-10 gap-y-4">
        <StatTile label="Regime" value={lookupRegimeState(state).label} metricKey="regime" />
        <StatTile label="Bias" value={lookupBias(str(regime, 'bias')).label} metricKey="bias" />
        <StatTile
          label="Market cap 24h"
          value={signedPct(marketCapChange, 2)}
          metricKey="change_24h"
          unavailable={coingeckoUnavailable}
          tone={
            marketCapChange === null
              ? undefined
              : marketCapChange > 0
                ? 'pos'
                : marketCapChange < 0
                  ? 'neg'
                  : undefined
          }
        />
        <StatTile
          label="BTC dominance"
          value={pct(num(marketContext, 'btc_dominance_pct'), 2)}
          metricKey="btc_dominance"
          unavailable={coingeckoUnavailable}
        />
        <StatTile
          label="ETH dominance"
          value={pct(num(marketContext, 'eth_dominance_pct'), 2)}
          metricKey="eth_dominance"
          unavailable={coingeckoUnavailable}
        />
        <StatTile
          label="Volatility"
          value={pct(num(marketContext, 'median_atr_pct'), 2)}
          metricKey="volatility"
        />
        <StatTile
          label="Sentiment"
          value={
            fearGreedValue !== null
              ? fearGreedClassification
                ? `${fearGreedValue} · ${fearGreedClassification}`
                : `${fearGreedValue}`
              : pct(fearGreedValue)
          }
          metricKey="fear_greed"
          tone={
            fearGreedClassification === 'Extreme Fear' ||
            fearGreedClassification === 'Extreme Greed'
              ? 'warn'
              : undefined
          }
        />
        <StatTile
          label="BTC correlation (mkt)"
          value={fmtNum(meanBtcCorrelation, 2)}
          metricKey="mean_btc_correlation"
        />
        <StatTile
          label="Alt-alt correlation"
          value={
            altAltMeanCorrelation === null
              ? '-'
              : `${fmtNum(altAltMeanCorrelation, 2)}${altAltCorrelationPairs !== null ? ` (n=${altAltCorrelationPairs})` : ''}`
          }
          metricKey="alt_alt_mean_correlation"
        />
        <StatTile
          label="Correlation spread"
          value={
            correlationSpread === null
              ? '-'
              : `${fmtNum(correlationSpread, 2)}${altAltCorrelationPairs !== null ? ` (n=${altAltCorrelationPairs})` : ''}`
          }
          metricKey="correlation_spread"
        />
      </div>

      <p className="mt-3 text-[12px] text-muted">
        {quality.trusted_count} coin{quality.trusted_count === 1 ? '' : 's'} trusted for scoring
        {quality.excluded_count > 0 ? `, ${quality.excluded_count} excluded for data quality` : ''}.
      </p>
    </section>
  );
}

/** One "SYMBOL long/short — reason" row inside a `candidates` briefing block. Deliberately a plain
 *  `<div>` row, not the `<ul>`/`<li>` list idiom WatchlistTable/GoldenPocketWatchStage otherwise
 *  use -- reuses their symbol/side-tag/reason classes, not their list markup. */
function BriefingCandidateRow({ item }: { item: BriefingCandidate }) {
  const side = sideMeta(item.side);
  return (
    <div className="flex flex-wrap items-baseline gap-x-2 gap-y-1 py-1.5 border-b border-line last:border-b-0">
      <span className="symbol-link">{item.symbol}</span>
      <span className={`setup-badge ${side.tone}`}>{side.label}</span>
      <span className="text-[12px] text-muted">{item.reason}</span>
    </div>
  );
}

function StatTile({
  label,
  value,
  tone,
  metricKey,
  unavailable,
}: {
  label: string;
  value: string;
  tone?: 'pos' | 'neg' | 'warn' | undefined;
  metricKey?: string;
  /** True when the source provider failed for this run -- see coingeckoGlobalUnavailable. Renders
   *  a quiet note so a bare "-" isn't mistaken for a genuine null/zero value. */
  unavailable?: boolean;
}) {
  const metric = metricKey ? lookupMetric(metricKey) : null;
  return (
    <div className={`stat${tone ? ` ${tone}` : ''}`}>
      <span className="stat-label inline-flex items-center gap-1">
        {label}
        {metric ? <InfoTip term={label} definition={metric.definition} /> : null}
      </span>
      <div className="stat-value">{value}</div>
      {unavailable ? (
        <div className="text-ash text-[11px]" title="The data provider didn't return this in time">
          unavailable this run
        </div>
      ) : null}
    </div>
  );
}
